### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by HelenLeonchenko** [XomaDev/MIUI-autostart#14]
I tested on a device with autostart permission turn-off and the method getAutoStartState() returned ENABLED.
Device: Redmi Note 9
MIUI version: 12.5.4
Android version: 11
MIUI Optimization: not depend on whether this parameter is enabled or disabled

**Comment by XomaDev** [comment]
Have you disabled or changed MIUI Optimization? It must be ON on the phone to work.
PS: I had recently tested the library with one of the latest MIUI device and I had no issues so far.

**Comment by HelenLeonchenko** [comment]
When MIUI Optimization is turned on and Autostart is turned off, getAutoStartState() returns enabled.

**Comment by XomaDev** [comment]
Maybe you wanna show us a screen recording of it? It's really unlikely to happen that way.

**Comment by HelenLeonchenko** [comment]
[Link on the video](https://drive.google.com/file/d/1Qrg0Cz4iaTe-k-9uHbCejnih0ITGuEsF/view?usp=drive_link). 
Code: 
        btnAutostart.setOnClickListener {
            val state = Autostart.getAutoStartState(applicationContext)
            Toast.makeText(applicationContext, "state=$state", Toast.LENGTH_SHORT).show()
        }

**Comment by XomaDev** [comment]
Thanks, does the app's settings screen also says that the Autostart is disabled While the app says its enabled?

**Comment by HelenLeonchenko** [comment]
Yes, you can see this information on the video: app name "test_autostart".

**Comment by XomaDev** [comment]
Tested on the latest MIUI 14 and it is reportedly working.
